In [6]:
import numpy as np

# sigmoid for binary problem
def nonlin(x):
    return 1/(1+np.exp(-x))

# derivative of sigmoid
def drv_nonlin(x):
    return x*(1-x)

# input dataset
X = np.array([ [0,1],
               [0,1],
               [1,0],
               [1,0] ])

# output dataset
# y = np.array([ [0],
#                [0],
#                [1],
#                [1] ])
# or simplify
y = np.array([[0,0,1,1]]).T

alphas = [0.0001, 10, 100000]

for alpha in alphas:
    print("\nTraining With Alpha:" + str(alpha))

    # seed random numbers to make calculation
    # this is neccessary to observe the result under same random numbers in one session
    np.random.seed(1)

    # hidden layer configuration.
    # 3 layear: You need to configure synapse 0 and synapse 1 here.
    synapse_0 = 2* np.random.random((2, 4)) - 1 # 2x4
    synapse_1 = 2* np.random.random((4, 1)) - 1 # 4x1

    # start training iterations (10k times)
    for i in range(100000):
        # iteration start
        num_iter = i

        # ---- training iteration step 1: Forward Propagation
        # Forward Propagation applies weights of synapses in each layer to produce output layer
        # Output layer is the layer that is the last layer as a final output for an iteration of training
        # the initial layer is the input
        l0 = X # 4x2
        # the hidden layer after application of the first synapse weights to layer 0 values, which is the input
        l0_weighted = np.dot(l0,synapse_0) # 4x2 2x4 -> 4x4
        # smooth each weighted value into new value ranging [0, 1)
        # now we generated the hidden layer, l1
        l1 = nonlin(l0_weighted) # -> 4x4

        # we finally compute the output layer by applying the second synapse weights to layer 1 values
        l1_weighted = np.dot(l1,synapse_1) # 4x4 4x1 -> 4x1
        # smooth each weighted value into new value ranging [0, 1)
        # now we generated the hidden layer, l1
        l2 = nonlin(l1_weighted) # -> 4x1
        # ---- Forward Propagation completed


        # ---- training iteration step 2: Back Propagation
        # Back Propagation adjust each weight of synapse layer by layer

        # First we figure out the initial error amount and direction on the output layer relative to the given output y
        l2_error = y - l2 # 4x1 - 4x1 -> 4x1
        # Incorporate the derivative of sigmoid on layer 2 (output layer)
        l2_delta = l2_error * drv_nonlin(l2) # 4x1 4x1 -> 4x1
        # Apply the delta computed to each synapses for the next iteration of training
        synapse_1 += alpha*l1.T.dot(l2_delta) # 4x4.T(=4x4) 4x1 -> 4x1

        # How much weights of synapse 1 contributed to the l2_delta
        l1_error = l2_delta.dot(synapse_1.T) # 4x1 4x1.T(=1x4) -> 4x4 
        # Incorporate the derivative of sigmoid on layer 1 (hidden layer)
        l1_delta = l1_error * drv_nonlin(l1) # 4x4 4x4 -> 4x4    
        # Apply the delta computed to each synapses for the next iteration of training
        synapse_0 += alpha*l0.T.dot(l1_delta) # 4x2.T(=2x4) 4x4 -> 2x4 
        # ---- Back Propagation completed

        # Checking error of the output layer respects to given output for each 10000 iterations
        # The number should decrease over the iterations
        if (num_iter% 10000) == 0:
            print("Error:" + str(np.mean(np.abs(l2_error))))


    print('')
    print("Output After Training:")
    print(l2)


Training With Alpha:0.0001
Error:0.499754731319
Error:0.495820572435
Error:0.49199917054
Error:0.4882000124
Error:0.48434135284
Error:0.480348227251
Error:0.476150878647
Error:0.471683627966
Error:0.46688418429
Error:0.461693389992

Output After Training:
[[ 0.50717481]
 [ 0.50717481]
 [ 0.59506281]
 [ 0.59506281]]

Training With Alpha:10
Error:0.499754731319
Error:0.00152288249106
Error:0.00106062132494
Error:0.000858124864207
Error:0.000738270927933
Error:0.000656913661611
Error:0.000597115675117
Error:0.000550808346178
Error:0.000513597632367
Error:0.00048286045523

Output After Training:
[[  4.58467401e-04]
 [  4.58467401e-04]
 [  9.99544619e-01]
 [  9.99544619e-01]]

Training With Alpha:100000
Error:0.499754731319


/Users/hiro99ishikawa/anaconda/envs/carnd-term1/lib/python3.5/site-packages/ipykernel/__main__.py:5: RuntimeWarning: overflow encountered in exp


Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0

Output After Training:
[[ 0.]
 [ 0.]
 [ 1.]
 [ 1.]]
